// =============================================================
// build.js  —  Vercel build script
// =============================================================
//
// What this does (plain English):
//   1. Reads the RENDER_API_URL environment variable from Vercel
//      (you set this in the Vercel dashboard)
//   2. Creates a tiny JS file called api-config.js that sets
//      window.__API_BASE__ to your Render backend URL
//   3. When index.html loads, it loads api-config.js first,
//      so the const API = window.__API_BASE__ line gets the
//      real Render URL instead of localhost
//
// This is the simplest possible way to inject a backend URL
// into a plain HTML/JS frontend without a build framework.
//
// Run automatically by Vercel — you don't run this manually.
// =============================================================

const fs   = require("fs");
const path = require("path");

// Read the Render backend URL from Vercel environment variables
// You set this in: Vercel Dashboard → Your Project → Settings → Environment Variables
const renderUrl = process.env.RENDER_API_URL;

if (!renderUrl) {
  console.warn(
    "⚠  WARNING: RENDER_API_URL environment variable is not set in Vercel.\n" +
    "   The frontend will fall back to http://localhost:8000.\n" +
    "   Set RENDER_API_URL in Vercel Dashboard → Settings → Environment Variables."
  );
}

// The URL to use — either the real Render URL or a safe fallback
const apiBase = renderUrl || "http://localhost:8000";

// Write api-config.js — a tiny file that sets the global variable
const configContent = `// Auto-generated by build.js — do not edit manually
// This file is recreated on every Vercel deployment.
window.__API_BASE__ = "${apiBase}";
console.log("API base URL:", window.__API_BASE__);
`;

const outputPath = path.join(__dirname, "api-config.js");
fs.writeFileSync(outputPath, configContent, "utf-8");

console.log(`✅ api-config.js written with API base: ${apiBase}`);
